#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define WOODEN_CANNONBALLS_PRICE 1
#define STONE_CANNONBALLS_PRICE 1
#define COBBLESTONE_CANNONBALLS_PRICE 1
#define METAL_CANNONBALLS_PRICE 1

#endif // CONFIG_H_INCLUDED
